// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.20.3
// source: model.proto

package protos

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	VideoOutput_OutputVideoStream_FullMethodName = "/model.VideoOutput/OutputVideoStream"
)

// VideoOutputClient is the client API for VideoOutput service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VideoOutputClient interface {
	OutputVideoStream(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[Request, Response], error)
}

type videoOutputClient struct {
	cc grpc.ClientConnInterface
}

func NewVideoOutputClient(cc grpc.ClientConnInterface) VideoOutputClient {
	return &videoOutputClient{cc}
}

func (c *videoOutputClient) OutputVideoStream(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[Request, Response], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &VideoOutput_ServiceDesc.Streams[0], VideoOutput_OutputVideoStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Request, Response]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type VideoOutput_OutputVideoStreamClient = grpc.ClientStreamingClient[Request, Response]

// VideoOutputServer is the server API for VideoOutput service.
// All implementations must embed UnimplementedVideoOutputServer
// for forward compatibility.
type VideoOutputServer interface {
	OutputVideoStream(grpc.ClientStreamingServer[Request, Response]) error
	mustEmbedUnimplementedVideoOutputServer()
}

// UnimplementedVideoOutputServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVideoOutputServer struct{}

func (UnimplementedVideoOutputServer) OutputVideoStream(grpc.ClientStreamingServer[Request, Response]) error {
	return status.Errorf(codes.Unimplemented, "method OutputVideoStream not implemented")
}
func (UnimplementedVideoOutputServer) mustEmbedUnimplementedVideoOutputServer() {}
func (UnimplementedVideoOutputServer) testEmbeddedByValue()                     {}

// UnsafeVideoOutputServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VideoOutputServer will
// result in compilation errors.
type UnsafeVideoOutputServer interface {
	mustEmbedUnimplementedVideoOutputServer()
}

func RegisterVideoOutputServer(s grpc.ServiceRegistrar, srv VideoOutputServer) {
	// If the following call pancis, it indicates UnimplementedVideoOutputServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&VideoOutput_ServiceDesc, srv)
}

func _VideoOutput_OutputVideoStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(VideoOutputServer).OutputVideoStream(&grpc.GenericServerStream[Request, Response]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type VideoOutput_OutputVideoStreamServer = grpc.ClientStreamingServer[Request, Response]

// VideoOutput_ServiceDesc is the grpc.ServiceDesc for VideoOutput service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VideoOutput_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "model.VideoOutput",
	HandlerType: (*VideoOutputServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "OutputVideoStream",
			Handler:       _VideoOutput_OutputVideoStream_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "model.proto",
}
