// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package protos

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ImageServiceClient is the client API for ImageService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ImageServiceClient interface {
	StreamImage(ctx context.Context, opts ...grpc.CallOption) (ImageService_StreamImageClient, error)
}

type imageServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewImageServiceClient(cc grpc.ClientConnInterface) ImageServiceClient {
	return &imageServiceClient{cc}
}

func (c *imageServiceClient) StreamImage(ctx context.Context, opts ...grpc.CallOption) (ImageService_StreamImageClient, error) {
	stream, err := c.cc.NewStream(ctx, &ImageService_ServiceDesc.Streams[0], "/model.ImageService/StreamImage", opts...)
	if err != nil {
		return nil, err
	}
	x := &imageServiceStreamImageClient{stream}
	return x, nil
}

type ImageService_StreamImageClient interface {
	Send(*StreamImageRequest) error
	Recv() (*ImageResponse, error)
	grpc.ClientStream
}

type imageServiceStreamImageClient struct {
	grpc.ClientStream
}

func (x *imageServiceStreamImageClient) Send(m *StreamImageRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *imageServiceStreamImageClient) Recv() (*ImageResponse, error) {
	m := new(ImageResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ImageServiceServer is the server API for ImageService service.
// All implementations must embed UnimplementedImageServiceServer
// for forward compatibility
type ImageServiceServer interface {
	StreamImage(ImageService_StreamImageServer) error
	mustEmbedUnimplementedImageServiceServer()
}

// UnimplementedImageServiceServer must be embedded to have forward compatible implementations.
type UnimplementedImageServiceServer struct {
}

func (UnimplementedImageServiceServer) StreamImage(ImageService_StreamImageServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamImage not implemented")
}
func (UnimplementedImageServiceServer) mustEmbedUnimplementedImageServiceServer() {}

// UnsafeImageServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ImageServiceServer will
// result in compilation errors.
type UnsafeImageServiceServer interface {
	mustEmbedUnimplementedImageServiceServer()
}

func RegisterImageServiceServer(s grpc.ServiceRegistrar, srv ImageServiceServer) {
	s.RegisterService(&ImageService_ServiceDesc, srv)
}

func _ImageService_StreamImage_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ImageServiceServer).StreamImage(&imageServiceStreamImageServer{stream})
}

type ImageService_StreamImageServer interface {
	Send(*ImageResponse) error
	Recv() (*StreamImageRequest, error)
	grpc.ServerStream
}

type imageServiceStreamImageServer struct {
	grpc.ServerStream
}

func (x *imageServiceStreamImageServer) Send(m *ImageResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *imageServiceStreamImageServer) Recv() (*StreamImageRequest, error) {
	m := new(StreamImageRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ImageService_ServiceDesc is the grpc.ServiceDesc for ImageService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ImageService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "model.ImageService",
	HandlerType: (*ImageServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamImage",
			Handler:       _ImageService_StreamImage_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "model.proto",
}
